In [93]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [94]:
data = pd.read_csv("C:/Users/Aslam Khan/Desktop/SalaryData_Train(1).csv")
df=data
df.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

### Eda exploratery data analysis

In [95]:
df.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [96]:
df.isnull()

age  workclass  education  educationno  maritalstatus  occupation  \
0      False      False      False        False          False       False   
1      False      False      False        False          False       False   
2      False      False      False        False          False       False   
3      False      False      False        False          False       False   
4      False      False      False        False          False       False   
...      ...        ...        ...          ...            ...         ...   
30156  False      False      False        False          False       False   
30157  False      False      False        False          False       False   
30158  False      False      False        False          False       False   
30159  False      False      False        False          False       False   
30160  False      False      False        False          False       False   

       relationship   race    sex  capitalgain  capitalloss  hoursperweek  \
0             False  False  False        False        False         False   
1             False  False  False        False        False         False   
2             False  False  False        False        False         False   
3             False  False  False        False        False         False   
4             False  False  False        False        False         False   
...             ...    ...    ...          ...          ...           ...   
30156         False  False  False        False        False         False   
30157         False  False  False        False        False         False   
30158         False  False  False        False        False         False   
30159         False  False  False        False        False         False   
30160         False  False  False        False        False         False   

       native  Salary  
0       False   False  
1       False   False  
2       False   False  
3       False   False  
4       False   False  
...       ...     ...  
30156   False   False  
30157   False   False  
30158   False   False  
30159   False   False  
30160   False   False  

[30161 rows x 14 columns]

In [97]:
df.isnull().sum()## we have define the missing value

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [98]:
df.info()## we have define the null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [99]:
df.describe()## we have define the neumric 

age   educationno   capitalgain   capitalloss  hoursperweek
count  30161.000000  30161.000000  30161.000000  30161.000000  30161.000000
mean      38.438115     10.121316   1092.044064     88.302311     40.931269
std       13.134830      2.550037   7406.466611    404.121321     11.980182
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [100]:
x = df.iloc[:,0:].values## define the x and y variable
x

array([[39, ' State-gov', ' Bachelors', ..., 40, ' United-States',
        ' <=50K'],
       [50, ' Self-emp-not-inc', ' Bachelors', ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', ' HS-grad', ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', ' HS-grad', ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', ' HS-grad', ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', ' HS-grad', ..., 40, ' United-States',
        ' >50K']], dtype=object)

In [101]:
x

array([[39, ' State-gov', ' Bachelors', ..., 40, ' United-States',
        ' <=50K'],
       [50, ' Self-emp-not-inc', ' Bachelors', ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', ' HS-grad', ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', ' HS-grad', ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', ' HS-grad', ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', ' HS-grad', ..., 40, ' United-States',
        ' >50K']], dtype=object)

In [102]:
y = df.iloc[:,1]
y

0                State-gov
1         Self-emp-not-inc
2                  Private
3                  Private
4                  Private
               ...        
30156              Private
30157              Private
30158              Private
30159              Private
30160         Self-emp-inc
Name: workclass, Length: 30161, dtype: object

In [103]:
y

0                State-gov
1         Self-emp-not-inc
2                  Private
3                  Private
4                  Private
               ...        
30156              Private
30157              Private
30158              Private
30159              Private
30160         Self-emp-inc
Name: workclass, Length: 30161, dtype: object

In [104]:
x = df[['age','educationno','capitalgain','capitalloss','hoursperweek']]
y = df['age']

#### we have spliting tha training and testing 

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
x_train,x_test,y_train,y_test = train_test_split(x,y ,test_size=0.2, random_state=1234)

In [107]:
x_train

age  educationno  capitalgain  capitalloss  hoursperweek
4743    58            9            0            0            50
25659   49            9            0            0            40
18414   51            9            0            0            40
25160   33            9            0            0            45
6874    53           11            0         1485            40
...    ...          ...          ...          ...           ...
27852   36            9            0         2001            40
23605   23           12            0            0            32
1318    28           13            0            0            43
25299   25           13            0            0            60
27439   60            4            0            0            15

[24128 rows x 5 columns]

In [108]:
y_train

4743     58
25659    49
18414    51
25160    33
6874     53
         ..
27852    36
23605    23
1318     28
25299    25
27439    60
Name: age, Length: 24128, dtype: int64

In [ ]:
### import the package 

In [109]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,  ConfusionMatrixDisplay,classification_report,accuracy_score
from sklearn  import tree

In [110]:
model = RandomForestClassifier(criterion='gini')
random = model.fit(x_train,y_train)

In [111]:
pred = model.predict(x_test)

In [112]:
pred

array([37, 54, 36, ..., 39, 21, 22], dtype=int64)

In [113]:
pred = model.predict(x_test)### we have predict our model

In [114]:
pred

array([37, 54, 36, ..., 39, 21, 22], dtype=int64)

In [115]:
result = confusion_matrix(y_test,pred) ## define the confusion martrix
result

array([[ 55,   0,   0, ...,   0,   0,   0],
       [  0,  85,   0, ...,   0,   0,   0],
       [  0,   3, 107, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   3]], dtype=int64)

In [116]:
from sklearn.metrics import r2_score,accuracy_score 
import numpy as np

In [117]:
accuracy_score(y_test,pred)## define the accuracy score

0.9318746892093486

# done